# .github/workflows/trade-import.yml
name: Auto Trade Import

on:
  schedule:
    - cron: '0 */3 * * *'  # Alle 3 Stunden
  workflow_dispatch:
    inputs:
      mode:
        description: 'Import Mode'
        required: true
        default: 'update'
        type: choice
        options:
        - update
        - full

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install Dependencies
      run: pip install pybit gspread google-auth pandas pytz requests
    
    - name: Run Import
      env:
        # Alle deine API Keys hier
        BYBIT_INCUBATORZONE_API_KEY: ${{ secrets.BYBIT_INCUBATORZONE_API_KEY }}
        BYBIT_INCUBATORZONE_API_SECRET: ${{ secrets.BYBIT_INCUBATORZONE_API_SECRET }}
        BYBIT_MEMESTRATEGIES_API_KEY: ${{ secrets.BYBIT_MEMESTRATEGIES_API_KEY }}
        BYBIT_MEMESTRATEGIES_API_SECRET: ${{ secrets.BYBIT_MEMESTRATEGIES_API_SECRET }}
        BYBIT_ETHAPESTRATEGIES_API_KEY: ${{ secrets.BYBIT_ETHAPESTRATEGIES_API_KEY }}
        BYBIT_ETHAPESTRATEGIES_API_SECRET: ${{ secrets.BYBIT_ETHAPESTRATEGIES_API_SECRET }}
        BYBIT_ALTSSTRATEGIES_API_KEY: ${{ secrets.BYBIT_ALTSSTRATEGIES_API_KEY }}
        BYBIT_ALTSSTRATEGIES_API_SECRET: ${{ secrets.BYBIT_ALTSSTRATEGIES_API_SECRET }}
        BYBIT_SOLSTRATEGIES_API_KEY: ${{ secrets.BYBIT_SOLSTRATEGIES_API_KEY }}
        BYBIT_SOLSTRATEGIES_API_SECRET: ${{ secrets.BYBIT_SOLSTRATEGIES_API_SECRET }}
        BYBIT_BTCSTRATEGIES_API_KEY: ${{ secrets.BYBIT_BTCSTRATEGIES_API_KEY }}
        BYBIT_BTCSTRATEGIES_API_SECRET: ${{ secrets.BYBIT_BTCSTRATEGIES_API_SECRET }}
        BYBIT_CORESTRATEGIES_API_KEY: ${{ secrets.BYBIT_CORESTRATEGIES_API_KEY }}
        BYBIT_CORESTRATEGIES_API_SECRET: ${{ secrets.BYBIT_CORESTRATEGIES_API_SECRET }}
        BYBIT_2K_API_KEY: ${{ secrets.BYBIT_2K_API_KEY }}
        BYBIT_2K_API_SECRET: ${{ secrets.BYBIT_2K_API_SECRET }}
        BYBIT_1K_API_KEY: ${{ secrets.BYBIT_1K_API_KEY }}
        BYBIT_1K_API_SECRET: ${{ secrets.BYBIT_1K_API_SECRET }}
        BYBIT_CLAUDE_PROJEKT_API_KEY: ${{ secrets.BYBIT_CLAUDE_PROJEKT_API_KEY }}
        BYBIT_CLAUDE_PROJEKT_API_SECRET: ${{ secrets.BYBIT_CLAUDE_PROJEKT_API_SECRET }}
        BLOFIN_API_KEY: ${{ secrets.BLOFIN_API_KEY }}
        BLOFIN_API_SECRET: ${{ secrets.BLOFIN_API_SECRET }}
        BLOFIN_API_PASSPHRASE: ${{ secrets.BLOFIN_API_PASSPHRASE }}
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      run: |
        python trade_importer.py --mode=${{ github.event.inputs.mode || 'update' }}
